apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/{username}/helloworld-python
        env:
        - name: TARGET
          value: "Python Sample v1"
        - name: AWS_HOST
          value: 0
        - name: AWS_PORT
          value: 0
        - name: BUCKET_NAME
          value: 0
        - name: AWS_ACCESS_KEY_ID
          value: 0
        - name: AWS_SECRET_ACCESS_KEY
          value: 0
